### PR TITLE
Align p-accordion icon with stretched p-link-pure icon

### PR DESCRIPTION
**Pull request by itrich**
If an Accordion component hosts several stretched Link Pure components with left-aligned icon, the icon of the Accordion component and the icons of the Link Pure components are misaligned.

image

This change adds an explicit width to the icon container and justifies the icon within the parent container, thus matching the icon alignment of the stretched Link Pure components.

image

Kudos to @sandrafrischmuth for spotting this issue.

### Pull Request Checklist

- [X] I have read and accept the [Contributor License Agreement](https://github.com/porscheofficial/oss-docs/blob/67c5b24838a293ce7a964884e6005eb71f2b8579/CONTRIBUTOR_LICENSE_AGREEMENT.md)

### CODE REVIEW

**Comment by itrich** [comment]
Thank you for enabling the CI pipeline for external contributors and updating the documentation. 🙏 

I still have to fix some failing tests, but will finalize this PR within the next days.

**Comment by denyo** [comment]
> Thank you for enabling the CI pipeline for external contributors and updating the documentation. 🙏
> 
> I still have to fix some failing tests, but will finalize this PR within the next days.

You're our first real external contribution so things might be a little bit bumpy.  
We also wrote a checklist of things that most likely need adjustment here: https://designsystem.porsche.com/latest/help/support#issue-and-contribution-management-at-git-hub

**Comment by o-hook** [comment]
Hi @itrich ,
I will take over and update all relevant tests to meet requirements of the pipeline.

**Comment by itrich** [comment]
> Hi @itrich , I will take over and update all relevant tests to meet requirements of the pipeline.

Thank you!

**Pull request closed without merging**
